const express=require('express'),cors=require('cors'),fs=require('fs'),path=require('path'),multer=require('multer');
const app=express();app.use(cors());app.use(express.json({limit:'5mb'}));
const DD=path.join(__dirname,'data');if(!fs.existsSync(DD))fs.mkdirSync(DD,{recursive:true});
const TD=path.join(DD,'tmp');if(!fs.existsSync(TD))fs.mkdirSync(TD,{recursive:true});
const CF=path.join(__dirname,'config.json');
let sv={};try{if(fs.existsSync(CF))sv=JSON.parse(fs.readFileSync(CF,'utf8'))}catch(e){}
const cfg={adminPassword:process.env.ADMIN_PASSWORD||sv.adminPassword||'changeme2025',provider:process.env.LLM_PROVIDER||sv.provider||'deepseek',apiKey:process.env.LLM_API_KEY||sv.apiKey||'',model:process.env.LLM_MODEL||sv.model||'',temperature:parseFloat(process.env.LLM_TEMPERATURE||sv.temperature||0.7),maxTokens:parseInt(process.env.LLM_MAX_TOKENS||sv.maxTokens||1200),brandName:sv.brandName||'BracketGPT',tagline:sv.tagline||'AI Bracket Advisor',activeSeason:sv.activeSeason||'2025',messagesPerMinute:parseInt(sv.messagesPerMinute||30),weights:sv.weights||{baseWeight:.6,upsetWeight:.25,floorWeight:.15},features:sv.features||{showTeamProfiles:true,showMatchupData:true,showOptimizerData:true,showUpsetPicks:true,showSafetyScores:true,includeHistoricalContext:true}};
function saveCfg(){try{fs.writeFileSync(CF,JSON.stringify(cfg,null,2))}catch(e){}}saveCfg();
const store={teams:null,base:null,upset:null,floor:null,optimizer:null};
const FM={teams:'team_profiles.json',base:'chatbot_predictions_base.json',upset:'chatbot_predictions_upset.json',floor:'chatbot_predictions_floor.json',optimizer:'bracket_optimizer_results.json'};
function loadData(){let a=false;for(const[k,f]of Object.entries(FM)){const p=path.join(DD,f);try{if(fs.existsSync(p)){store[k]=JSON.parse(fs.readFileSync(p,'utf8'));a=true}else store[k]=null}catch(e){store[k]=null}}return a}
const hasData=loadData();
function sysPrompt(){const n=(store.base?.predictions||[]).length;return`You are BracketGPT — a sharp, fun March Madness bracket advisor. Talk like a knowledgeable friend who watches way too much college basketball. Confident, opinionated, backed by data.\n\nHOW TO TALK:\n- Casual. Contractions. No corporate speak.\n- NEVER say "based on my analysis" — just give your take.\n- Use basketball language: "chalk pick," "live dog," "fade," "value play," "cinderella."\n- Lead with your pick, THEN explain. 2-4 short paragraphs max.\n- Bold team names. Don't over-format.\n\nWRONG: "Based on our ensemble model prediction of 73.2% win probability, Duke appears stronger."\nRIGHT: "**Duke** takes this. Defense is suffocating — top 5 adjusted efficiency — 80+ Elo edge. Around 73% to win. Lock it in."\n\nCONFIDENCE:\n- 85%+ → "Lock it in"\n- 70-85% → "Solid pick"\n- 55-70% → "Slight lean"\n- 50-55% → "Coin flip"\n\nSTRATEGY: ESPN scoring 10-20-40-80-160-320. Small pools = chalk. Big pools = need upsets.\n\nDATA: ${n} matchup predictions from 3-model ensemble (XGBoost+LightGBM) on 2003-2024 data. 76% accuracy.`}
function findCtx(q){const ctx=[],lc=(q||'').toLowerCase();const pr=store.teams?.profiles||store.teams?.teams||(Array.isArray(store.teams)?store.teams:[]);for(const t of pr){const n=(t.name||t.school||'').toLowerCase();if(n&&lc.includes(n))ctx.push({type:'team',data:t})}for(const md of['base','upset','floor']){for(const p of(store[md]?.predictions||[])){const t1=(p.t1_name||'').toLowerCase(),t2=(p.t2_name||'').toLowerCase();let hit=(t1&&lc.includes(t1))||(t2&&lc.includes(t2));if(!hit){const m=lc.match(/(\d+)\s*(?:seed|vs|versus)/);if(m&&(p.t1_seed===+m[1]||p.t2_seed===+m[1]))hit=true}if(hit)ctx.push({type:'pred',model:md,data:p})}}if(/upset|cinderella|underdog|dark.?horse|sleeper/.test(lc))for(const p of(store.base?.predictions||[]))if(p.upset_flag==='upset')ctx.push({type:'pred',model:'base',data:p});if(/bracket|strateg|pool|optim/.test(lc))for(const o of(store.optimizer?.results||[]).slice(0,5))ctx.push({type:'opt',data:o});if(/final.fo
cat > backend/server.js << 'ENDSERVER'
const express=require('express'),cors=require('cors'),fs=require('fs'),path=require('path'),multer=require('multer');
const app=express();app.use(cors());app.use(express.json({limit:'5mb'}));
const DD=path.join(__dirname,'data');if(!fs.existsSync(DD))fs.mkdirSync(DD,{recursive:true});
const TD=path.join(DD,'tmp');if(!fs.existsSync(TD))fs.mkdirSync(TD,{recursive:true});
const CF=path.join(__dirname,'config.json');
let sv={};try{if(fs.existsSync(CF))sv=JSON.parse(fs.readFileSync(CF,'utf8'))}catch(e){}
const cfg={adminPassword:process.env.ADMIN_PASSWORD||sv.adminPassword||'changeme2025',provider:process.env.LLM_PROVIDER||sv.provider||'deepseek',apiKey:process.env.LLM_API_KEY||sv.apiKey||'',model:process.env.LLM_MODEL||sv.model||'',temperature:parseFloat(process.env.LLM_TEMPERATURE||sv.temperature||0.7),maxTokens:parseInt(process.env.LLM_MAX_TOKENS||sv.maxTokens||1200),brandName:sv.brandName||'BracketGPT',tagline:sv.tagline||'AI Bracket Advisor',activeSeason:sv.activeSeason||'2025',messagesPerMinute:parseInt(sv.messagesPerMinute||30),weights:sv.weights||{baseWeight:.6,upsetWeight:.25,floorWeight:.15},features:sv.features||{showTeamProfiles:true,showMatchupData:true,showOptimizerData:true,showUpsetPicks:true,showSafetyScores:true,includeHistoricalContext:true}};
function saveCfg(){try{fs.writeFileSync(CF,JSON.stringify(cfg,null,2))}catch(e){}}saveCfg();
const store={teams:null,base:null,upset:null,floor:null,optimizer:null};
const FM={teams:'team_profiles.json',base:'chatbot_predictions_base.json',upset:'chatbot_predictions_upset.json',floor:'chatbot_predictions_floor.json',optimizer:'bracket_optimizer_results.json'};
function loadData(){let a=false;for(const[k,f]of Object.entries(FM)){const p=path.join(DD,f);try{if(fs.existsSync(p)){store[k]=JSON.parse(fs.readFileSync(p,'utf8'));a=true}else store[k]=null}catch(e){store[k]=null}}return a}
const hasData=loadData();
function sysPrompt(){const n=(store.base?.predictions||[]).length;return`You are BracketGPT — a sharp, fun March Madness bracket advisor. Talk like a knowledgeable friend who watches way too much college basketball. Confident, opinionated, backed by data.\n\nHOW TO TALK:\n- Casual. Contractions. No corporate speak.\n- NEVER say "based on my analysis" — just give your take.\n- Use basketball language: "chalk pick," "live dog," "fade," "value play," "cinderella."\n- Lead with your pick, THEN explain. 2-4 short paragraphs max.\n- Bold team names. Don't over-format.\n\nWRONG: "Based on our ensemble model prediction of 73.2% win probability, Duke appears stronger."\nRIGHT: "**Duke** takes this. Defense is suffocating — top 5 adjusted efficiency — 80+ Elo edge. Around 73% to win. Lock it in."\n\nCONFIDENCE:\n- 85%+ → "Lock it in"\n- 70-85% → "Solid pick"\n- 55-70% → "Slight lean"\n- 50-55% → "Coin flip"\n\nSTRATEGY: ESPN scoring 10-20-40-80-160-320. Small pools = chalk. Big pools = need upsets.\n\nDATA: ${n} matchup predictions from 3-model ensemble (XGBoost+LightGBM) on 2003-2024 data. 76% accuracy.`}
function findCtx(q){const ctx=[],lc=(q||'').toLowerCase();const pr=store.teams?.profiles||store.teams?.teams||(Array.isArray(store.teams)?store.teams:[]);for(const t of pr){const n=(t.name||t.school||'').toLowerCase();if(n&&lc.includes(n))ctx.push({type:'team',data:t})}for(const md of['base','upset','floor']){for(const p of(store[md]?.predictions||[])){const t1=(p.t1_name||'').toLowerCase(),t2=(p.t2_name||'').toLowerCase();let hit=(t1&&lc.includes(t1))||(t2&&lc.includes(t2));if(!hit){const m=lc.match(/(\d+)\s*(?:seed|vs|versus)/);if(m&&(p.t1_seed===+m[1]||p.t2_seed===+m[1]))hit=true}if(hit)ctx.push({type:'pred',model:md,data:p})}}if(/upset|cinderella|underdog|dark.?horse|sleeper/.test(lc))for(const p of(store.base?.predictions||[]))if(p.upset_flag==='upset')ctx.push({type:'pred',model:'base',data:p});if(/bracket|strateg|pool|optim/.test(lc))for(const o of(store.optimizer?.results||[]).slice(0,5))ctx.push({type:'opt',data:o});if(/final.four|champ|win.it.all|natty/.test(lc))for(const p of(store.base?.predictions||[]))if(p.t1_seed<=2&&p.t2_seed<=2)ctx.push({type:'pred',model:'base',data:p});const seen=new Set();return ctx.filter(c=>{const k=JSON.stringify(c);if(seen.has(k))return false;seen.add(k);return true}).slice(0,20)}
function fmtCtx(ctx){return ctx.map(c=>{if(c.type==='team')return'TEAM: '+JSON.stringify(c.data);if(c.type==='pred'){const p=c.data;return`[${c.model}] (${p.t1_seed})${p.t1_name} vs (${p.t2_seed})${p.t2_name} > ${p.predicted_winner_name} ${(Math.max(p.model_win_prob,1-p.model_win_prob)*100).toFixed(0)}% ${p.confidence} ${p.upset_flag||''}`}if(c.type==='opt')return'OPT: '+JSON.stringify(c.data);return''}).filter(Boolean).join('\n')}
async function callLLM(messages,ctxStr){const key=cfg.apiKey;if(!key)return"Need an API key! Admin: set LLM_API_KEY in Railway env vars or go to /admin.";const sys=sysPrompt()+(ctxStr?'\n\n-- DATA --\n'+ctxStr:'');try{if(cfg.provider==='deepseek'){const r=await fetch('https://api.deepseek.com/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+key},body:JSON.stringify({model:cfg.model||'deepseek-chat',messages:[{role:'system',content:sys},...messages],temperature:cfg.temperature,max_tokens:cfg.maxTokens})});const d=await r.json();if(d.error)return'API error: '+(d.error.message||JSON.stringify(d.error));return d.choices?.[0]?.message?.content||'No response.'}if(cfg.provider==='claude'){const r=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':key,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:cfg.model||'claude-sonnet-4-20250514',max_tokens:cfg.maxTokens,system:sys,messages})});const d=await r.json();if(d.error)return'API error: '+(d.error.message||JSON.stringify(d.error));return d.content?.[0]?.text||'No response.'}if(cfg.provider==='gemini'){const m=cfg.model||'gemini-2.0-flash';const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/'+m+':generateContent?key='+key,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:sys+'\n\n'+messages.map(m=>m.role+': '+m.content).join('\n')}]}],generationConfig:{temperature:cfg.temperature,maxOutputTokens:cfg.maxTokens}})});const d=await r.json();return d.candidates?.[0]?.content?.parts?.[0]?.text||'No response.'}return'Unknown provider: '+cfg.provider}catch(e){console.error('LLM err:',e);return"Connection issue. Try again."}}
const rates=new Map();function rateOk(ip){const now=Date.now();let e=rates.get(ip);if(!e||now-e.t>=60000)e={c:0,t:now};if(e.c>=cfg.messagesPerMinute){rates.set(ip,e);return false}e.c++;rates.set(ip,e);return true}
function auth(req,res,next){if((req.header('x-admin-password')||'')!==cfg.adminPassword)return res.status(401).json({error:'Unauthorized'});next()}
app.get('/api/config',(req,res)=>res.json({brandName:cfg.brandName,tagline:cfg.tagline,activeSeason:cfg.activeSeason,dataLoaded:hasData}));
app.post('/api/chat',async(req,res)=>{try{if(!rateOk(req.ip||'x'))return res.status(429).json({error:'Too many messages.'});const msgs=req.body?.messages;if(!Array.isArray(msgs)||!msgs.length)return res.status(400).json({error:'No message.'});const ctx=findCtx(msgs.map(m=>m.content).join(' '));res.json({reply:await callLLM(msgs,fmtCtx(ctx))})}catch(e){console.error(e);res.status(500).json({error:'Something broke.'})}});
app.get('/admin/config',auth,(req,res)=>{const ds={};for(const k of Object.keys(FM)){const d=store[k];ds[k]=!!(d&&(Array.isArray(d)?d.length:(d.predictions?.length||d.profiles?.length||d.results?.length)))}res.json({...cfg,dataStatus:ds})});
app.post('/admin/config',auth,(req,res)=>{const b=req.body||{};for(const k of['provider','apiKey','model','temperature','maxTokens','brandName','tagline','activeSeason','messagesPerMinute'])if(b[k]!==undefined)cfg[k]=b[k];if(b.weights)cfg.weights=b.weights;if(b.features)cfg.features=b.features;saveCfg();res.json({ok:true})});
app.post('/admin/password',auth,(req,res)=>{const{oldPassword,newPassword}=req.body||{};if(!oldPassword||!newPassword)return res.status(400).json({error:'Both required'});if(oldPassword!==cfg.adminPassword)return res.status(403).json({error:'Wrong password'});cfg.adminPassword=newPassword;saveCfg();res.json({ok:true})});
const up=multer({dest:TD});
app.post('/admin/upload',auth,up.single('file'),(req,res)=>{const t=req.body.type;if(!t||!FM[t])return res.status(400).json({success:false,error:'Bad type'});if(!req.file)return res.status(400).json({success:false,error:'No file'});try{const raw=fs.readFileSync(req.file.path,'utf8');JSON.parse(raw);fs.writeFileSync(path.join(DD,FM[t]),raw);fs.unlinkSync(req.file.path);loadData();res.json({success:true})}catch(e){if(fs.existsSync(req.file.path))fs.unlinkSync(req.file.path);res.status(400).json({success:false,error:'Bad JSON'})}});
app.get('/admin',(req,res)=>res.sendFile(path.join(__dirname,'..','frontend','admin.html'),e=>{if(e&&!res.headersSent)res.status(404).send('Not found')}));
app.use(express.static(path.join(__dirname,'..','frontend')));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'..','frontend','index.html'),e=>{if(e&&!res.headersSent)res.status(404).send('Not found')}));
process.on('uncaughtException',e=>console.error('Uncaught:',e));process.on('unhandledRejection',e=>console.error('Unhandled:',e));
const PORT=process.env.PORT||3000;app.listen(PORT,()=>console.log('BracketGPT on :'+PORT+' | '+cfg.provider+' | key:'+(cfg.apiKey?'yes':'NO')+' | data:'+(hasData?'yes':'NO')));
